name       : armagetronad
version    : 0.2.8.3.4
release    : 5
source     :
    - https://cytranet.dl.sourceforge.net/project/armagetronad/stable/0.2.8.3.4/armagetronad-0.2.8.3.4.src.tar.bz2 : 23afa6d961cdcdf391849e1a4fafe8fc3330d9a8cb6671565b0303c709baf794
license    : GPL-2.0-or-later
component  : games.arcade
summary    : Armagetron Advanced is the continuation of Manual Moos', alias, z-man's original game, Armagetron
description: |
    Armagetron Advanced is the continuation of Manual Moos', alias, z-man's original game, Armagetron.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(x11)
setup      : |
    %configure --with-x \
               --disable-games \
               --enable-desktop \
               --enable-music \
               --disable-static \
               --disable-sysinstall \
               --disable-useradd \
               --disable-etc \
               --enable-master \
               --enable-main \
               --sysconfdir=/usr/share/armagetronad
build      : |
    %make
install    : |
    %make_install -j1
    install -D -m00644 $pkgfiles/armagetronad.desktop $installdir/usr/share/applications/armagetronad.desktop
