name       : armagetronad
version    : 0.2.8.3.3
release    : 1
source     :
    - https://launchpad.net/armagetronad/0.2.8/0.2.8.3.x/+download/armagetronad-0.2.8.3.3.src.tar.bz2 : ddf2d781b134392e9667f17e0319ae2117c20e6eb7738e3cacd701f3608ea5e8
license    : GPL-2.0
component  : games.arcade
summary    : Armagetron Advanced is the continuation of Manual Moos', alias, z-man's original game, Armagetron.
description: |
    Armagetron Advanced is the continuation of Manual Moos', alias, z-man's original game, Armagetron.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(sdl)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(x11)
    - libjpeg-turbo-devel
setup      : |
    %patch -p0 < $pkgfiles/armagetronad-0.2.8.3.3-gcc6.patch
    %configure --with-x \
               --disable-games \
               --enable-desktop \
               --enable-music \
               --disable-static \
               --disable-sysinstall \
               --disable-useradd \
               --disable-etc \
               --enable-master \
               --enable-main \
               --sysconfdir=/usr/share/armagetronad
build      : |
    %make
install    : |
    %make_install
