name       : armagetronad
version    : 0.2.9.1.0
release    : 10
source     :
    - https://launchpad.net/armagetronad/0.2.9/0.2.9.1.0/+download/armagetronad-0.2.9.1.0.tbz : 59b6c7c01ce3f8cca5437e33f974a637529541a11aa4f52c1a5c17499e26f6a1
license    : GPL-2.0-or-later
component  : games.arcade
summary    : Armagetron Advanced is the continuation of Manual Moos', alias, z-man's
    original game, Armagetron
description: |
    Armagetron Advanced is the continuation of Manual Moos', alias, z-man's original game, Armagetron.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(x11)
setup      : |
    %configure --with-x \
               --disable-games \
               --enable-desktop \
               --enable-music \
               --disable-static \
               --disable-sysinstall \
               --disable-useradd \
               --disable-etc \
               --enable-master \
               --enable-main \
               --sysconfdir=/usr/share/armagetronad
build      : |
    %make
install    : |
    %make_install -j1
    install -D -m00644 $pkgfiles/armagetronad.desktop $installdir/usr/share/applications/armagetronad.desktop
